version: '2'
services:
  db:
    image: postgres:12
    container_name: yoytec_server_db
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=produccion
    restart: always             # run as a service
    volumes:
        - ./postgresql:/var/lib/postgresql/data

  odoo:
    build: ./odoo
    depends_on:
      - db
    expose:
      - "8069"
      - "8072"
    tty: true
    environment:
      - PGHOST=produccion
      - PGPORT=5432
      - PGDATABASE=produccion
      - PGUSER=odoo
      - PGPASSWORD=odoo
      - PSQL_VERSION=12
      - DB_NAME=produccion
      - DB_HOST=yoytec_server_db
      - ODOO_CONFIG_FILE=/mnt/odoo.conf
    command: /entry_point.py
    volumes:
      - ./addons:/home/odoo/instance/extra_addons/
      - ./filestore:/home/odoo/.local/share/Odoo/filestore
      - ./etc/:/mnt
    restart: always

  nginx:
    image: nginx
    ports:
    - "80:80"
    depends_on:
    - odoo
    - netdata
    volumes:
        - ./conf:/etc/nginx/conf.d/

  netdata:
    image: netdata/netdata
    container_name: netdata_status
    restart: always
    expose:
      - "19999"
    volumes:
      - /etc/passwd:/host/etc/passwd:ro
      - /etc/group:/host/etc/group:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    cap_add:
      - SYS_PTRACE
    security_opt:
      - apparmor=unconfined
